// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Difficulty: Codable {
    public var level: Int

    public init(level: Int) {
        self.level = level
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.level = try values.decode(Int.self, forKey: "level")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(level, forKey: "level")
    }
}
