// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GraphqlQuestionContributor: Codable {
    public var username: String
    public var profileURL: String
    public var avatarURL: String
    public var typename: String?

    public init(username: String, profileURL: String, avatarURL: String, typename: String? = nil) {
        self.username = username
        self.profileURL = profileURL
        self.avatarURL = avatarURL
        self.typename = typename
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.username = try values.decode(String.self, forKey: "username")
        self.profileURL = try values.decode(String.self, forKey: "profileUrl")
        self.avatarURL = try values.decode(String.self, forKey: "avatarUrl")
        self.typename = try values.decodeIfPresent(String.self, forKey: "__typename")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(username, forKey: "username")
        try values.encode(profileURL, forKey: "profileUrl")
        try values.encode(avatarURL, forKey: "avatarUrl")
        try values.encodeIfPresent(typename, forKey: "__typename")
    }
}
