// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GraphqlQuestionCodeSnippet: Codable {
    /// Example: "C++"
    public var lang: String
    /// Example: "cpp"
    public var langSlug: String
    public var code: String
    public var typename: AnyJSON?

    public init(lang: String, langSlug: String, code: String, typename: AnyJSON? = nil) {
        self.lang = lang
        self.langSlug = langSlug
        self.code = code
        self.typename = typename
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.lang = try values.decode(String.self, forKey: "lang")
        self.langSlug = try values.decode(String.self, forKey: "langSlug")
        self.code = try values.decode(String.self, forKey: "code")
        self.typename = try values.decodeIfPresent(AnyJSON.self, forKey: "__typename")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(lang, forKey: "lang")
        try values.encode(langSlug, forKey: "langSlug")
        try values.encode(code, forKey: "code")
        try values.encodeIfPresent(typename, forKey: "__typename")
    }
}
