// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GraphqlData: Codable {
    public var question: GraphqlQuestionDetail?
    public var user: GraphqlUser?
    public var problemsetQuestionList: GraphqlProblemsetQuestionList?

    public init(
        question: GraphqlQuestionDetail? = nil,
        user: GraphqlUser? = nil,
        problemsetQuestionList: GraphqlProblemsetQuestionList? = nil
    ) {
        self.question = question
        self.user = user
        self.problemsetQuestionList = problemsetQuestionList
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.question = try values.decodeIfPresent(GraphqlQuestionDetail.self, forKey: "question")
        self.user = try values.decodeIfPresent(GraphqlUser.self, forKey: "user")
        self.problemsetQuestionList = try values.decodeIfPresent(GraphqlProblemsetQuestionList.self, forKey: "problemsetQuestionList")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(question, forKey: "question")
        try values.encodeIfPresent(user, forKey: "user")
        try values.encodeIfPresent(problemsetQuestionList, forKey: "problemsetQuestionList")
    }
}
