// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GraphqlProblemsetQuestionList: Codable {
    /// Example: 2046
    public var totalNum: Int?
    public var questions: [GraphqlQuestionDetail]?

    public init(totalNum: Int? = nil, questions: [GraphqlQuestionDetail]? = nil) {
        self.totalNum = totalNum
        self.questions = questions
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.totalNum = try values.decodeIfPresent(Int.self, forKey: "totalNum")
        self.questions = try values.decodeIfPresent([GraphqlQuestionDetail].self, forKey: "questions")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(totalNum, forKey: "totalNum")
        try values.encodeIfPresent(questions, forKey: "questions")
    }
}
