// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GraphqlQueryProblemsetQuestionListVariablesFilterInput: Codable {
    public var tags: [String]?
    public var difficulty: AnyJSON?
    public var status: AnyJSON?
    /// Example: "7p5x763"
    public var listID: String?
    public var isPremiumOnly: Bool?

    public init(
        tags: [String]? = nil,
        difficulty: AnyJSON? = nil,
        status: AnyJSON? = nil,
        listID: String? = nil,
        isPremiumOnly: Bool? = nil
    ) {
        self.tags = tags
        self.difficulty = difficulty
        self.status = status
        self.listID = listID
        self.isPremiumOnly = isPremiumOnly
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.tags = try values.decodeIfPresent([String].self, forKey: "tags")
        self.difficulty = try values.decodeIfPresent(AnyJSON.self, forKey: "difficulty")
        self.status = try values.decodeIfPresent(AnyJSON.self, forKey: "status")
        self.listID = try values.decodeIfPresent(String.self, forKey: "listId")
        self.isPremiumOnly = try values.decodeIfPresent(Bool.self, forKey: "premiumOnly")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(tags, forKey: "tags")
        try values.encodeIfPresent(difficulty, forKey: "difficulty")
        try values.encodeIfPresent(status, forKey: "status")
        try values.encodeIfPresent(listID, forKey: "listId")
        try values.encodeIfPresent(isPremiumOnly, forKey: "premiumOnly")
    }
}
