// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Problems: Codable {
    public var userName: String
    public var numSolved: Int
    public var numTotal: Int
    public var acEasy: Int
    public var acMedium: Int
    public var acHard: Int
    public var statStatusPairs: [StatStatusPair]
    public var frequencyHigh: Int
    public var frequencyMid: Int
    public var categorySlug: String

    public init(
        userName: String,
        numSolved: Int,
        numTotal: Int,
        acEasy: Int,
        acMedium: Int,
        acHard: Int,
        statStatusPairs: [StatStatusPair],
        frequencyHigh: Int,
        frequencyMid: Int,
        categorySlug: String
    ) {
        self.userName = userName
        self.numSolved = numSolved
        self.numTotal = numTotal
        self.acEasy = acEasy
        self.acMedium = acMedium
        self.acHard = acHard
        self.statStatusPairs = statStatusPairs
        self.frequencyHigh = frequencyHigh
        self.frequencyMid = frequencyMid
        self.categorySlug = categorySlug
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.userName = try values.decode(String.self, forKey: "user_name")
        self.numSolved = try values.decode(Int.self, forKey: "num_solved")
        self.numTotal = try values.decode(Int.self, forKey: "num_total")
        self.acEasy = try values.decode(Int.self, forKey: "ac_easy")
        self.acMedium = try values.decode(Int.self, forKey: "ac_medium")
        self.acHard = try values.decode(Int.self, forKey: "ac_hard")
        self.statStatusPairs = try values.decode([StatStatusPair].self, forKey: "stat_status_pairs")
        self.frequencyHigh = try values.decode(Int.self, forKey: "frequency_high")
        self.frequencyMid = try values.decode(Int.self, forKey: "frequency_mid")
        self.categorySlug = try values.decode(String.self, forKey: "category_slug")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(userName, forKey: "user_name")
        try values.encode(numSolved, forKey: "num_solved")
        try values.encode(numTotal, forKey: "num_total")
        try values.encode(acEasy, forKey: "ac_easy")
        try values.encode(acMedium, forKey: "ac_medium")
        try values.encode(acHard, forKey: "ac_hard")
        try values.encode(statStatusPairs, forKey: "stat_status_pairs")
        try values.encode(frequencyHigh, forKey: "frequency_high")
        try values.encode(frequencyMid, forKey: "frequency_mid")
        try values.encode(categorySlug, forKey: "category_slug")
    }
}
