// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths {
    static var problems: Problems {
        Problems(path: "/problems")
    }

    struct Problems {
        /// Path: `/problems`
        public let path: String
    }
}
