// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths.Submissions.Detail {
    func id(_ id: String) -> WithID {
        WithID(path: "\(path)/\(id)")
    }

    struct WithID {
        /// Path: `/submissions/detail/{id}`
        public let path: String
    }
}
