// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths.Problems {
    func problem(_ problem: String) -> WithProblem {
        WithProblem(path: "\(path)/\(problem)")
    }

    struct WithProblem {
        /// Path: `/problems/{problem}`
        public let path: String
    }
}
