// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths.API {
    var problems: Problems {
        Problems(path: path + "/problems")
    }

    struct Problems {
        /// Path: `/api/problems`
        public let path: String
    }
}
