// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths.Problems.WithProblem {
    var interpretSolution: InterpretSolution {
        InterpretSolution(path: path + "/interpret_solution")
    }

    struct InterpretSolution {
        /// Path: `/problems/{problem}/interpret_solution`
        public let path: String

        public func post(_ body: LeetcodeAPI.TestSubmission? = nil) -> Request<LeetcodeAPI.Interpretation> {
            Request(method: "POST", url: path, body: body)
        }
    }
}
