// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths.Problems.WithProblem {
    var submit: Submit {
        Submit(path: path + "/submit")
    }

    struct Submit {
        /// Path: `/problems/{problem}/submit`
        public let path: String

        public func post(_ body: LeetcodeAPI.Submission? = nil) -> Request<LeetcodeAPI.SubmissionID> {
            Request(method: "POST", url: path, body: body)
        }
    }
}
