// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths {
    static var api: API {
        API(path: "/api")
    }

    struct API {
        /// Path: `/api`
        public let path: String
    }
}
