// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths {
    static var submissions: Submissions {
        Submissions(path: "/submissions")
    }

    struct Submissions {
        /// Path: `/submissions`
        public let path: String
    }
}
