// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

public extension Paths {
    static var graphql: Graphql {
        Graphql(path: "/graphql")
    }

    struct Graphql {
        /// Path: `/graphql`
        public let path: String

        public func post(_ body: LeetcodeAPI.GraphqlQuery? = nil) -> Request<LeetcodeAPI.GraphqlResponse> {
            Request(method: "POST", url: path, body: body)
        }
    }
}
